# Generated by Django 5.1.6 on 2025-02-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('classification_flag', models.CharField(max_length=50)),
                ('classification_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnailLink', models.URLField()),
                ('item_weight', models.FloatField()),
                ('time_date', models.DateTimeField()),
                ('camera_flag', models.BooleanField(default=False)),
                ('mcu_flag', models.BooleanField(default=False)),
                ('weight_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
